version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: pharmaxcess_db_container
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  
  server:
    build: .
    image: pharmaxcess_server:latest
    container_name: pharmaxcess_server_container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    volumes:
    - .:/usr/src/app

volumes:
  db-data:
