repos:
  - repo: local
    hooks:
      # - id: safety
      #   name: safety
      #   entry: bash -c 'export PYTHONIOENCODING=utf-8 && bash distributeur/backend/scripts/safety/run_safety.sh'
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   always_run: true

      - id: check-leak
        name: Check for Leaks
        entry: python distributeur/backend/scripts/leak_checker/check_leak.py
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: [tqdm]