
repos:
  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: safety check -r ./distributeur/backend/requirements.txt --policy-file ./distributeur/backend/scripts/safety/safety-policy.yaml
        language: python
        types: [python]
        additional_dependencies: [safety]
        pass_filenames: false
