import { StyleSheet } from 'react-native';
import { ColorScheme } from './Colors';

const createStyles = (colors: ColorScheme, fontScale: number) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    safeArea: {
        flex: 1,
    },
    header: {
        padding: 20,
        backgroundColor: colors.background,
    },
    headerTitle: {
        fontSize: 24 * fontScale,
        fontWeight: 'bold',
        color: colors.headerText,
        textAlign: 'center',
    },
    headerSubtitle: {
        fontSize: 16 * fontScale,
        color: colors.headerText,
        opacity: 0.7,
        textAlign: 'center',
        marginTop: 5,
    },
    content: {
        flex: 1,
        padding: 15,
        paddingBottom: 100, // Space for floating buttons 
    },
    requestCard: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 20,
        marginBottom: 15,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: colors.border,
    },
    patientInfo: {
        flex: 1,
    },
    patientName: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
        marginBottom: 5,
    },
    requestTime: {
        fontSize: 14 * fontScale,
        color: colors.infoText,
    },
    arrow: {
        marginLeft: 10,
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 50,
    },
    emptyText: {
        fontSize: 16 * fontScale,
        color: colors.infoText,
        textAlign: 'center',
        marginTop: 20,
    },
    // Styles for request detail modal 
    detailModal: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    detailContent: {
        flex: 1,
        backgroundColor: colors.background,
        marginTop: 50,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    detailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        backgroundColor: colors.card,
    },
    detailTitle: {
        fontSize: 20 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
    },
    closeButton: {
        padding: 5,
    },
    prescriptionContainer: {
        flex: 1,
        padding: 20,
    },
    prescriptionImage: {
        width: '100%',
        height: 400,
        borderRadius: 12,
        resizeMode: 'contain',
        backgroundColor: colors.inputBackground,
        borderWidth: 1,
        borderColor: colors.border,
    },
    buttonContainer: {
        flexDirection: 'row',
        padding: 20,
        gap: 15,
        backgroundColor: colors.background,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    approveButton: {
        flex: 1,
        backgroundColor: colors.success,
        borderRadius: 8,
        padding: 15,
        alignItems: 'center',
    },
    rejectButton: {
        flex: 1,
        backgroundColor: colors.error,
        borderRadius: 8,
        padding: 15,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 16 * fontScale,
        fontWeight: 'bold',
    },
    // Styles for rejection modal 
    rejectModal: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rejectContent: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 20,
        margin: 20,
        width: '90%',
        borderWidth: 1,
        borderColor: colors.border,
    },
    rejectTitle: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
        marginBottom: 15,
        textAlign: 'center',
    },
    commentInput: {
        borderWidth: 1,
        borderColor: colors.inputBorder,
        backgroundColor: colors.inputBackground,
        borderRadius: 8,
        padding: 15,
        minHeight: 100,
        textAlignVertical: 'top',
        fontSize: 16 * fontScale,
        color: colors.infoText,
        marginBottom: 20,
    },
    rejectButtonContainer: {
        flexDirection: 'row',
        gap: 10,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: colors.secondary,
        borderRadius: 8,
        padding: 15,
        alignItems: 'center',
    },
    sendButton: {
        flex: 1,
        backgroundColor: colors.error,
        borderRadius: 8,
        padding: 15,
        alignItems: 'center',
    },
    // Styles for camera and QR code (user view)
    centeredContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    card: {
        width: '90%',
        height: 100,
        borderRadius: 10,
        overflow: 'hidden',
    },
    cardGradient: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
    },
    cardText: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.profileText,
        textAlign: 'center',
    },
    button: {
        paddingVertical: 15,
        paddingHorizontal: 40,
        borderRadius: 25,
        minWidth: 200,
        alignItems: 'center',
    },
    buttonTextWhite: {
        color: '#FFFFFF',
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
    },
    camera: {
        flex: 1,
        width: '100%',
    },
    cameraContainer: {
        flex: 1,
    },
    cameraButton: {
        position: 'absolute',
        bottom: 40,
        alignSelf: 'center',
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: colors.primary,
    },
    cameraIcon: {
        fontSize: 28,
        textAlign: 'center',
        textAlignVertical: 'center',
        lineHeight: 28,
    },
    qrContainer: {
        alignItems: 'center',
        padding: 20,
    },
    qrImage: {
        width: 220,
        height: 220,
        marginTop: 20,
        borderRadius: 12,
    },
    qrTitle: {
        fontSize: 24 * fontScale,
        fontWeight: 'bold',
        color: colors.profileText,
        marginBottom: 20,
        textAlign: 'center',
    },
    qrCodeWrapper: {
        padding: 20,
        backgroundColor: colors.background,
        borderRadius: 12,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    qrText: {
        fontSize: 16 * fontScale,
        color: colors.profileText,
        marginTop: 20,
        textAlign: 'center',
    },
    loadingText: {
        fontSize: 18 * fontScale,
        color: colors.profileText,
        marginBottom: 20,
        textAlign: 'center',
    },
    gradient: {
        paddingVertical: 15,
        paddingHorizontal: 30,
        marginVertical: 10,
        borderRadius: 10,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        width: 300,
        height: 400,
        borderRadius: 12,
        marginBottom: 20,
        resizeMode: 'contain',
    },
    qrImage: {
        width: 220,
        height: 220,
        resizeMode: 'contain',
        marginTop: 16,
    },
    loadingButtonsContainer: {
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    },
    loadingMessageContainer: {
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.infoBackground,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.infoBorder,
    },
    loadingMessageText: {
    fontSize: 16 / fontScale,
    fontWeight: '600',
    color: colors.infoTitle,
    textAlign: 'center',
    marginBottom: 4,
    },
    loadingMessageSubtext: {
    fontSize: 14 / fontScale,
    color: colors.infoText,
    textAlign: 'center',
    opacity: 0.8,
    },
});

export default createStyles;