import { StyleSheet } from 'react-native';
import { ColorScheme } from './Colors';

const createStyles = (colors: ColorScheme, fontScale: number) =>
  StyleSheet.create({
    distributorItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        marginVertical: 8,
        backgroundColor: colors.surface,
        borderRadius: 10,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 3,
    },
    distributorText: {
        fontSize: 16 * fontScale,
        fontWeight: 'bold',
        color: colors.profileText,
    },
    distanceText: {
        fontSize: 14 * fontScale,
        color: colors.infoTextSecondary,
        marginTop: 4,
    },
    statusBadgeClose: {
        backgroundColor: colors.success,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        alignSelf: 'center',
    },
    statusBadgeFar: {
        backgroundColor: colors.error,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        alignSelf: 'center',
    },
    statusBadgeText: {
        color: 'white',
        fontSize: 12 * fontScale,
        fontWeight: 'bold',
    },
    navigationContainer: {
        position: 'absolute',
        top: 60,
        left: 16,
        right: 16,
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 16,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    navigationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    navigationIcon: {
        fontSize: 24,
    },
    navigationInfo: {
        flex: 1,
        marginLeft: 12,
    },
    navigationDistance: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.profileText,
    },
    navigationDestination: {
        fontSize: 14 * fontScale,
        color: colors.infoTextSecondary,
    },
    stopButton: {
        backgroundColor: colors.error,
        borderRadius: 20,
        padding: 8,
    },
    stopButtonText: {
        color: 'white',
        fontSize: 12 * fontScale,
        fontWeight: 'bold',
    },
    instructionContainer: {
        backgroundColor: colors.primary + '20',
        borderRadius: 8,
        padding: 12,
        marginTop: 8,
    },
    instructionText: {
        fontSize: 16 * fontScale,
        color: colors.text,
        fontWeight: '500',
    },
    recenterButton: {
        position: 'absolute',
        backgroundColor: colors.background,
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 }, 
        shadowOpacity: 0.25, 
        shadowRadius: 3.84, 
        elevation: 5, 
    }, 
    recenterIcon: { 
        fontSize: 20, 
    },
    qrButton: { 
        position: 'absolute', 
          backgroundColor: colors.background,
          borderRadius: 25, 
          width: 50, 
          height: 50, 
          justifyContent: 'center',
          alignItems: 'center',
          shadowColor: colors.shadow, 
          shadowOffset: { width: 0, height: 2 }, 
          shadowOpacity: 0.25, 
          shadowRadius: 3.84, 
          elevation: 5,
    },
    qrIcon: {
        fontSize: 15,
    },
    slidingPanel: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: colors.background,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.27,
        shadowRadius: 4.65,
        elevation: 6,
    },
    swipeHandle: {
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 50,
    },
    swipeIndicator: {
        width: 40,
        height: 4,
        borderRadius: 2,
    },
    swipeText: {
        fontSize: 12 * fontScale,
        color: colors.infoTextSecondary,
        marginTop: 4,
    },
    panelHeader: {
        paddingHorizontal: 20,
        paddingBottom: 10,
    },
    panelTitle: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.profileText,
        textAlign: 'center',
    },
    panelSubtitle: {
        fontSize: 14 * fontScale,
        color: colors.infoTextSecondary,
        textAlign: 'center',
        marginTop: 4,
    },
    selectedDistributor: {
        backgroundColor: colors.surface,
        borderRadius: 10,
        padding: 15,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 3,
    },
    text: {
        fontSize: 16 * fontScale,
        color: colors.iconPrimary,
        fontWeight: 'bold',
        textAlign: 'center',
    }, 
    transportModeLabel: {
        fontSize: 16 * fontScale,
        fontWeight: 'bold',
        marginTop: 15,
        marginBottom: 10,
        color: colors.profileText,
    },
    transportModeContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    transportModeButton: {
        flex: 1,
        minWidth: '48%',
        borderRadius: 8,
        padding: 12,
        margin: 2,
        alignItems: 'center',
        borderWidth: 2,
    },
    transportModeIcon: {
        fontSize: 20,
        marginBottom: 4,
    },
    transportModeText: {
         fontSize: 12 * fontScale,
    },
    goButton: {
        borderRadius: 8,
        overflow: 'hidden',
        marginTop: 8,
    },
    gradientButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
    },
    startNavigationButton: {
         backgroundColor: colors.success,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'black',
    },
    scannerHeader: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        padding: 20,
    },
    scannerHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    scannerTitle: {
        color: 'white',
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
    },
    scannerClose: {
        color: 'white',
        fontSize: 16 * fontScale,
    },
    scannerInstructions: {
        color: 'white',
        fontSize: 14 * fontScale,
        marginTop: 5,
    },
    scannerView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scannerBox: {
        width: 250,
        height: 250,
        borderWidth: 2,
        borderColor: 'white',
        borderRadius: 20,
        backgroundColor: 'transparent',
    },
    scannerCorner: {
        position: 'absolute',
        width: 40,
        height: 40,
    },
    scannerCornerTopLeft: {
        top: -10,
        left: -10,
        borderLeftWidth: 4,
        borderTopWidth: 4,
        borderColor: colors.success,
        borderTopLeftRadius: 20,
    },
    scannerCornerTopRight: {
        top: -10,
        right: -10,
        borderRightWidth: 4,
        borderTopWidth: 4,
        borderColor: colors.success,
        borderTopRightRadius: 20,
    },
    scannerCornerBottomLeft: {
        bottom: -10,
        left: -10,
        borderLeftWidth: 4,
        borderBottomWidth: 4,
        borderColor: colors.success,
        borderBottomLeftRadius: 20,
    },
    scannerCornerBottomRight: {
        bottom: -10,
        right: -10,
        borderRightWidth: 4,
        borderBottomWidth: 4,
        borderColor: colors.success,
        borderBottomRightRadius: 20,
    },
    scannerStatus: {
        position: 'absolute',
        bottom: 60,
        left: 20,
        right: 20,
        backgroundColor: 'rgba(0,0,0,0.7)',
        borderRadius: 10,
        padding: 15,
    },
    scannerStatusText: {
        color: 'white',
        fontSize: 16 * fontScale,
        textAlign: 'center',
    },
    noPermissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    noPermissionText: {
        color: 'white',
        fontSize: 18 * fontScale,
        textAlign: 'center',
        marginBottom: 20,
    },
    allowCameraButton: {
        backgroundColor: colors.success,
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
    },
    allowCameraText: {
        color: 'white',
        fontSize: 16 * fontScale,
    },
    cancelText: {
        color: 'white',
        fontSize: 16 * fontScale,
    },
  });

export default createStyles;