import { StyleSheet } from 'react-native';
import { ColorScheme } from './Colors';

const createStyles = (colors: ColorScheme, fontScale: number) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    safeArea: {
        flex: 1,
    },
    header: {
        padding: 20,
        backgroundColor: colors.background,
    },
    headerTitle: {
        fontSize: 24 * fontScale,
        fontWeight: 'bold',
        color: colors.headerText,
        textAlign: 'center',
        marginBottom: 20,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    searchInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: colors.inputBorder,
        backgroundColor: colors.inputBackground,
        borderRadius: 10,
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16 * fontScale,
        color: colors.headerText,
        marginRight: 10,
    },
    scanButton: {
        backgroundColor: colors.secondary,
        borderRadius: 10,
        padding: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    content: {
        flex: 1,
        paddingHorizontal: 15,
        paddingBottom: 80,
    },
    patientCard: {
        backgroundColor: colors.card,
        padding: 15,
        marginVertical: 8,
        borderRadius: 12,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.border,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    patientInfo: {
        flex: 1,
    },
    patientName: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
        marginBottom: 5,
    },
    patientAge: {
        fontSize: 14 * fontScale,
        color: colors.infoText,
        marginBottom: 3,
    },
    patientId: {
        fontSize: 12 * fontScale,
        color: colors.infoTextSecondary,
    },
    arrow: {
        marginLeft: 10,
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 50,
    },
    emptyIcon: {
        marginBottom: 20,
    },
    emptyTitle: {
        fontSize: 20 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
        marginBottom: 10,
        textAlign: 'center',
    },
    emptySubtitle: {
        fontSize: 16 * fontScale,
        color: colors.infoText,
        textAlign: 'center',
        lineHeight: 24 * fontScale,
    },
    // Scanner Modal Styles
    scannerModal: {
        flex: 1,
        backgroundColor: 'black',
    },
    camera: {
        flex: 1,
    },
    scannerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scannerFrame: {
        width: 250,
        height: 250,
        borderWidth: 2,
        borderColor: colors.secondary,
        backgroundColor: 'transparent',
    },
    scannerText: {
        color: colors.iconPrimary,
        fontSize: 18 * fontScale,
        textAlign: 'center',
        marginTop: 20,
        paddingHorizontal: 20,
    },
    closeButton: {
        position: 'absolute',
        top: 50,
        right: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: 25,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    // Patient Detail Styles
    detailModal: {
        flex: 1,
        backgroundColor: colors.background,
    },
    detailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    backButton: {
        marginRight: 15,
        padding: 5,
    },
    detailTitle: {
        fontSize: 20 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
    },
    detailContent: {
        flex: 1,
        padding: 20,
    },
    profileSection: {
        backgroundColor: colors.card,
        borderRadius: 15,
        padding: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: colors.border,
    },
    profileHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    profileImage: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: colors.secondary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    profileImageText: {
        color: colors.iconPrimary,
        fontSize: 24 * fontScale,
        fontWeight: 'bold',
    },
    profileHeaderInfo: {
        flex: 1,
    },
    profileName: {
        fontSize: 20 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
        marginBottom: 5,
    },
    profileAge: {
        fontSize: 16 * fontScale,
        color: colors.infoText,
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    gridItem: {
        width: '48%',
        aspectRatio: 1,
        marginBottom: 15,
        borderRadius: 15,
        overflow: 'hidden',
        elevation: 3,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    gradientBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 15,
    },
    itemIcon: {
        marginBottom: 10,
    },
    itemTitle: {
        fontSize: 16 * fontScale,
        fontWeight: 'bold',
        color: colors.iconPrimary,
        textAlign: 'center',
        lineHeight: 20 * fontScale,
    },
    // Section Detail Styles
    sectionModal: {
        flex: 1,
        backgroundColor: colors.background,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    sectionTitle: {
        fontSize: 20 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
    },
    sectionContent: {
        flex: 1,
        padding: 20,
    },
    itemCard: {
        backgroundColor: colors.card,
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: colors.border,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    itemCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    itemCardTitle: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
        flex: 1,
    },
    severityBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginLeft: 10,
    },
    severityText: {
        color: colors.iconPrimary,
        fontSize: 12 * fontScale,
        fontWeight: 'bold',
    },
    itemDescription: {
        fontSize: 14 * fontScale,
        color: colors.infoText,
        lineHeight: 20 * fontScale,
        marginBottom: 8,
    },
    itemDate: {
        fontSize: 12 * fontScale,
        color: colors.infoTextSecondary,
        marginBottom: 8,
    },
    itemNotes: {
        fontSize: 14 * fontScale,
        color: colors.headerText,
        fontStyle: 'italic',
        backgroundColor: colors.surface,
        padding: 10,
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: colors.secondary,
    },
});

export default createStyles;