import { StyleSheet } from 'react-native';
import { ColorScheme } from './Colors';

const createStyles = (colors: ColorScheme, fontScale: number) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
        position: 'relative',
    },
    listContainer: {
        flex: 1,
        padding: 20,
        paddingBottom: 0,
    },
    bottomButtonContainer: {
        padding: 20,
        paddingTop: 10,
        backgroundColor: colors.background,
        borderTopWidth: 1,
        borderTopColor: colors.inputBorder,
    },
    openTicketButton: {
        width: '100%',
        borderRadius: 10,
        overflow: 'hidden',
    },
    fixedButtonContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
        backgroundColor: colors.background,
        borderTopWidth: 1,
        borderTopColor: colors.inputBorder,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
    },
    addButton: {
        width: '100%',
        borderRadius: 10,
        overflow: 'hidden',
    },
    card: {
        width: '100%',
        backgroundColor: colors.card,
        borderRadius: 10,
        padding: 15,
        marginVertical: 8,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    title: {
        fontSize: 18 * fontScale,
        fontWeight: 'bold',
        color: colors.infoTitle,
    },
    content: {
        fontSize: 16 * fontScale,
        color: colors.infoText,
        marginTop: 4,
    },
    date: {
        fontSize: 14 * fontScale,
        color: colors.infoTextSecondary,
        marginTop: 4,
    },
    button: {
        flex: 1,
        marginHorizontal: 10,
    },
    buttonText: {
        color: colors.text,
        fontWeight: 'bold',
        fontSize: 16 * fontScale,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 30,
    },
    gradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderRadius: 10,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
        padding: 20,
    },
    modalTitle: {
        fontSize: 24 * fontScale,
        fontWeight: 'bold',
        marginBottom: 20,
        color: colors.settingsTitle,
    },
    input: {
        width: '100%',
        padding: 10,
        borderWidth: 1,
        borderColor: colors.inputBorder,
        borderRadius: 5,
        marginBottom: 20,
        backgroundColor: colors.inputBackground,
        fontSize: 16 * fontScale,
    },
    saveButton: {
        flex: 1,
        marginHorizontal: 10,
        marginTop: 20,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        overflow: 'hidden',
    },
    saveButtonText: {
        color: colors.text,
        fontSize: 16 * fontScale,
        fontWeight: 'bold',
    },
});

export default createStyles;