
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/
COPY requirements_ignored.txt /app/

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements_ignored.txt

RUN apt-get update && apt-get install -y netcat-openbsd

RUN pip install --upgrade Flask Werkzeug

COPY . /app

COPY pytest.ini /app/

# Create the directory for the data
RUN mkdir -p /data

# Copy the init script
COPY scripts/init_medicine.sh /init_medicine.sh

RUN chmod +x /init_medicine.sh

ENTRYPOINT ["/init_medicine.sh"]

CMD ["pytest", "--ignore=app.py", "--cov=./", "--cov-report=term-missing", "-vv"]
