FROM openjdk:17-jdk-alpine AS build

WORKDIR /app

RUN apk add --no-cache maven

COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["/app/entrypoint.sh"]
