
name: CI/CD

on:
  push:
    branches:
        - LOG_add_CI/CD_backend
        - dev
        - master

jobs:
  vulnerability_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Safety check
      run: ./scripts/run_safety.sh
