name: Automatic Mirror Sync

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
	    git@github.com:EpitechPromo2026/G-EIP-700-LYN-7-1-eip-jessica.ebely.git            
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
