
name: Automatic Mirror Sync

on: 
  [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        run: |
          if [ "$GITHUB_REPOSITORY" == "EpitechPromo2026/G-EIP-700-LYN-7-1-eip-jessica.ebely" ]; then
            echo "Already on the mirror repo: not doing anything"
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push changes to mirror repository (excluding sync.yml)
        run: |
          git remote add mirror git@github.com:EpitechPromo2026/G-EIP-700-LYN-7-1-eip-jessica.ebely.git
          git fetch mirror

          # Créer une branche temporaire
          git checkout -b temp-mirror

          # Supprimer sync.yml du commit (sans le supprimer du repo)
          git rm --cached .github/workflows/sync.yml || true
          git commit -m "Mirror update (excluding sync.yml)" || true

          # Pousser les changements vers le dépôt miroir
          git push --force mirror temp-mirror:main

          # Nettoyage de la branche temporaire
          git branch -D temp-mirror
